### ISSUE TITLE
Rorybot error messaging: wish to > would like to > want to

### ISSUE THREAD

**Issue by JasonChristie** [Shopify/retext-shopify#16]
The suggestion for `wish to` is `would like to` which then causes a suggestion to change `would like to` to `want to`.

Should probably just go from `wish to` to `want to`.

**Comment by jeremyhansonfinger** [comment]
Fixed in https://github.com/Shopify/retext-shopify/commit/55f68fef824c99bdb827c5dbba221e67d7e4d19f
