### ISSUE TITLE
Replace "payment gateway" with "payment provider"

### ISSUE THREAD

**Issue by selenehinkley** [Shopify/retext-shopify#28]
**Update the Style Guide**

Replace `payment gateway` with `payment provider`

Payments team is working on a bunch of projects and the word `provider` is much preferred to `gateway` because of merchant understanding around the term. This is a situation where common merchant use of a term trumps industry standard. Payments team to use `payment provider` going forward and we'll need to update existing use of gateway.

@HYPD @sfolkes 
@Shopify/timeline @Shopify/product-content  @Shopify/documentation

**Comment by jeremyhansonfinger** [comment]
I'll update Rorybot today with this change.
